In [1]:
import importlib

import database.training_sessions

importlib.reload(
    database.training_sessions
)

ModuleNotFoundError: No module named 'database'

In [1]:
# Daily Training Workflow Notebook

## 1. Imports

import sys
import os

sys.path.append(
    os.path.abspath("..")
)

from database.player_repository import (
    get_players
)

from database.training_sessions import (
    create_training_session,
    get_sessions
)

from database.device_assignment_repository import (
    assign_device,
    get_session_assignments
)

In [3]:
# 2. Ver jugadoras disponibles

players = get_players()

players

   id     name            category  dorsal              surname
0   4    Irene  BBCA Costa Artabra      21     Fernandez Mendez
1   6     Lola  BBCA Costa Artabra      24      Filgueiras Anca
2   2   Carmen  BBCA Costa Artabra       7           Gomez Mori
3   1  Adriana  BBCA Costa Artabra       3  Regueiro San Martin
4   5   Sabela  BBCA Costa Artabra      23         Romero Veiga
5   3     Inés  BBCA Costa Artabra      11        Toimil Bouzon

In [2]:
# 3. VARIABLES DEL ENTRENAMIENTO

# =========================
# DATOS ENTRENAMIENTO
# =========================

SESSION_DATE = "2026-05-14"
LOCATION = "Polideportivo Gómez Noya"
ATTENDEES = 9
NOTES = "3v3v3 Continuo + Zona"
FLG_GAME = 0


# =========================
# JUGADORAS
# =========================

COROS_PLAYER_ID = 6
MYZONE_PLAYER_ID = 5
SUUNTO_PLAYER_ID = 3

In [3]:

# 4. CREAR SESIÓN

session_id = create_training_session(
    session_date=SESSION_DATE,
    attendees=ATTENDEES,
    location=LOCATION,
    flg_game=FLG_GAME,
    notes=NOTES

)

print(f"Session ID: {session_id}")

Session ID: 6

In [4]:
# 5. ASIGNAR DISPOSITIVOS

assign_device(
    session_id=session_id,
    player_id=COROS_PLAYER_ID,
    device_type="COROS"
)

assign_device(
    session_id=session_id,
    player_id=MYZONE_PLAYER_ID,
    device_type="MYZONE"
)

assign_device(
    session_id=session_id,
    player_id=SUUNTO_PLAYER_ID,
    device_type="SUUNTO"
)

In [5]:
# 6. COMPROBAR ASSIGNMENTS

assignments = get_session_assignments(
    session_id
)

assignments

   id device_type    name          surname
0  15       COROS    Lola  Filgueiras Anca
1  16      MYZONE  Sabela     Romero Veiga
2  17      SUUNTO    Inés    Toimil Bouzon