In [36]:
import importlib

import database.training_sessions

importlib.reload(
    database.training_sessions
)

In [37]:
# Daily Training Workflow Notebook

## 1. Imports

import sys
import os

sys.path.append(
    os.path.abspath("..")
)

from database.player_repository import (
    get_players
)

from database.training_sessions import (
    create_training_session,
    get_sessions
)

from database.device_assignment_repository import (
    assign_device,
    get_session_assignments
)

In [27]:
# 2. Ver jugadoras disponibles

players = get_players()

players

   id     name            category  dorsal              surname
0   4    Irene  BBCA Costa Artabra      21     Fernandez Mendez
1   6     Lola  BBCA Costa Artabra      24      Filgueiras Anca
2   2   Carmen  BBCA Costa Artabra       7           Gomez Mori
3   1  Adriana  BBCA Costa Artabra       3  Regueiro San Martin
4   5   Sabela  BBCA Costa Artabra      23         Romero Veiga
5   3     Inés  BBCA Costa Artabra      11        Toimil Bouzon

In [33]:
# 3. VARIABLES DEL ENTRENAMIENTO

# =========================
# DATOS ENTRENAMIENTO
# =========================

SESSION_DATE = "2026-05-09"
LOCATION = "Pabellón Cocheras Coruña"
ATTENDEES = 9
NOTES = "PlayOff 2ª fase. @Esclavas"
FLG_GAME = 1


# =========================
# JUGADORAS
# =========================

COROS_PLAYER_ID = None
MYZONE_PLAYER_ID = 5

In [38]:

# 4. CREAR SESIÓN

session_id = create_training_session(
    session_date=SESSION_DATE,
    attendees=ATTENDEES,
    location=LOCATION,
    flg_game=FLG_GAME,
    notes=NOTES

)

print(f"Session ID: {session_id}")

Session ID: 3

In [39]:
# 5. ASIGNAR DISPOSITIVOS

assign_device(
    session_id=session_id,
    player_id=COROS_PLAYER_ID,
    device_type="COROS"
)

assign_device(
    session_id=session_id,
    player_id=MYZONE_PLAYER_ID,
    device_type="MYZONE"
)

In [40]:
# 6. COMPROBAR ASSIGNMENTS

assignments = get_session_assignments(
    session_id
)

assignments

   id device_type    name       surname
0   6      MYZONE  Sabela  Romero Veiga

In [41]:
# 7. RESUMEN FINAL

print("Entrenamiento cargado correctamente")
print(f"Session ID: {session_id}")
print(f"COROS Player ID: {COROS_PLAYER_ID}")
print(f"MYZONE Player ID: {MYZONE_PLAYER_ID}")

Entrenamiento cargado correctamente
Session ID: 3
COROS Player ID: None
MYZONE Player ID: 5