In [1]:
import sys
import os

sys.path.append(
    os.path.abspath("..")
)

In [2]:
from database.db import DB_PATH

print(DB_PATH)

c:\Users\Usuario\Desktop\Repositorios\Physical_data\BT_db.db

In [18]:
import importlib

import database.coros_repository

importlib.reload(
    database.coros_repository
)

In [19]:
from database.coros_repository import (
    save_coros_data
)

In [13]:
from parsers.coros_parser import load_coros_fit

In [14]:
df_coros = load_coros_fit(
    "../data/FerrolBaloncesto20260507190518.fit"
)

In [10]:
from database.coros_repository import (
    save_coros_data
)

In [20]:
df_coros[["x", "y"]].head()

           x          y
0  12.562710  14.482759
1  12.294802  13.733650
2  12.026894  13.002378
3  11.664856  12.164090
4  11.302819  11.325803

In [21]:
save_coros_data(
    df_coros,
    session_id=1,
    player_id=1
)

In [23]:
from database.player_repository import (
    get_players
)
players = get_players()

players

   id     name            category  dorsal              surname
0   4    Irene  BBCA Costa Artabra      21     Fernandez Mendez
1   6     Lola  BBCA Costa Artabra      24      Filgueiras Anca
2   2   Carmen  BBCA Costa Artabra       7           Gomez Mori
3   1  Adriana  BBCA Costa Artabra       3  Regueiro San Martin
4   5   Sabela  BBCA Costa Artabra      23         Romero Veiga
5   3     Inés  BBCA Costa Artabra      11        Toimil Bouzon

In [32]:
from database.training_sessions import (
    create_training_session,
    get_sessions
)

In [27]:
session_id = create_training_session(
    session_date="2026-05-08",
    notes="Entrenamiento Cadete. Transiciones + Partido contra Masculino."
)

print(session_id)

1

In [28]:
sessions = get_sessions()

sessions

   id session_date                                              notes
0   1   2026-05-08  Entrenamiento Cadete. Transiciones + Partido c...

In [38]:
import importlib

import database.training_sessions

importlib.reload(
    database.training_sessions
)

In [40]:

from database.training_sessions import (
    create_training_session
)

In [ ]:
session_id = create_training_session(
    session_date="2026-05-08",
    attendees=13,
    location="Gómez Noya",
    notes="5x5 transición"
)

print(session_id)

1

In [47]:
import importlib

import database.device_assignment_repository

In [48]:
from database.device_assignment_repository import (
    assign_device,
    get_session_assignments
)

In [49]:
assign_device(
    session_id=1,
    player_id=1,
    device_type="COROS"
)

In [50]:
assign_device(
    session_id=1,
    player_id=3,
    device_type="MYZONE"
)

In [54]:
from database.myzone_repository import (
    save_myzone_data
)

In [56]:
import importlib

import parsers.myzone_parser

importlib.reload(
    parsers.myzone_parser
)

In [57]:
from parsers.myzone_parser import (
    parse_myzone_timeline,
    parse_myzone_summary
)

In [59]:
timeline = parse_myzone_timeline(
    "../data/22060508_MYZONE_Activity .csv"
)

In [60]:
timeline.head()

            timestamp  heart_rate
0 2026-05-07 19:13:00         121
1 2026-05-07 19:14:00         136
2 2026-05-07 19:15:00         164
3 2026-05-07 19:16:00         124
4 2026-05-07 19:17:00         156

In [61]:
save_myzone_data(
    timeline,
    session_id=1,
    player_id=3
)